[build]
builder = "Nixpacks"

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn auto_site.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2"

[environments]
[environments.production]
DJANGO_DEBUG = "False"
DJANGO_ALLOWED_HOSTS = "*"